# Generated by Django 5.1 on 2024-09-01 15:05

from django.db import migrations

def combine_category(apps, schema_editor):
    Category = apps.get_model('main', 'Category')

    Category.objects.create(name='Футболка')
    Category.objects.create(name='Худи')
    Category.objects.create(name='Джинсы')
    Category.objects.create(name='Носки')


def combine_product(apps, schema_editor):
    Product = apps.get_model('main', 'Product')

    for i in range(1, 10000):
        Product.objects.create(name='Серая', description='Тест', cat=1)



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_category)
    ]