# Generated by Django 5.1 on 2024-09-01 21:25

from django.db import migrations


def combine_product(apps, schema_editor):
    Product = apps.get_model('main', 'Product')

    for i in range(1, 10000):
        Product.objects.create(name='Серая', description='Тест', cat_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240901_1805'),
    ]

    operations = [
        migrations.RunPython(combine_product)
    ]
